/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_homepage (void);
GtkWidget* create_appointement (void);
GtkWidget* create_admin (void);
GtkWidget* create_window_gestionfiche (void);
GtkWidget* create_window_ajtfiche (void);
GtkWidget* create_window_modfiche (void);
GtkWidget* create_window_rechfiche (void);
GtkWidget* create_window_stat (void);
GtkWidget* create_Director (void);
GtkWidget* create_windowallbr (void);
GtkWidget* create_windowstatdir (void);
GtkWidget* create_Doctor (void);
GtkWidget* create_map (void);
